### ISSUE TITLE
Duplicate assertion used by with

### ISSUE THREAD

**Issue by OlesiaSub** [JetBrains-Research/PyNose#13]
In cases like this duplicate assertion is detected and removed incorrectly.
```
with self.assertRaises(ValueError):
    x = 3
with self.assertRaises(ValueError):
    x = 4
```

leads to this:
```
with:
    x = 4
```

**Comment by SmirnovOleg** [comment]
@OlesiaSub have you fixed it?

**Comment by OlesiaSub** [comment]
@SmirnovOleg I did. sorry, forgot to link it to pr-fixes pull request
