### ISSUE TITLE
PyNose not compatible with PyCharm build 212.*?

### ISSUE THREAD

**Issue by JonesH** [JetBrains-Research/PyNose#3]
Will there be support for newer builds?

**Comment by WANGJIEKE** [comment]
Hi, what is the incompatibility issue you are facing with? Currently we know that the plugin will cause an error saying "Slow operations are prohibited on EDT" in newer version PyCharm when running in GUI mode.

**Comment by danieldavidf** [comment]
The GUI mode plugin only works for PyCharm versions 211.* or older, according to error message:

![image](https://user-images.githubusercontent.com/14796469/135911172-e6fc30bc-e693-4803-ad79-8fdaa04c14b8.png)

**Comment by SmirnovOleg** [comment]
Hey, sorry for such a late response - we are currently working on it now, and a new GUI mode with inspections will be added soon! It will also be compatible with the new builds of PyCharm.

**Comment by SmirnovOleg** [comment]
We have released a new GUI version of the plugin that is compatible with PyCharm 2021.3+ (since build 213.5744.248). 
Feel free to try it and give us feedback!
