### ISSUE TITLE
False positive "Consider removing conditions" for comprehensions

### ISSUE THREAD

**Issue by lancelote** [JetBrains-Research/PyNose#32]
```python
@pytest.mark.parametrize(
    ("number", "expected"),
    [
        (1, 0),
        *((i, 1) for i in range(2, 10)),
        *((i, 2) for i in range(10, 26)),
        *((i, 3) for i in range(26, 50)),
        (50, 4),
    ],
)
def test_circle_number(number, expected):
    assert get_circle_number(number) == expected
```

Plugin reports

> Consider removing conditions from tests to ensure that all statements are executed

<img width="929" alt="warning" src="https://user-images.githubusercontent.com/2500320/147358620-f4a254ee-9a07-4ad6-ad68-cea2a3181fea.png">

**Comment by lancelote** [comment]
A simpler example

```python
def test_apply_claim():
    fabric = [[0 for _ in range(11)] for _ in range(9)]
    ...
```

**Comment by areyde** [comment]
Yeah, actually this implementation was the default one from paper — mark the test if it simply has any of the "condition" keywords, which produces false positives. 

I believe we can check that it's not just any condition, but that the _assert is in the condition_ (located within the cycle or the check). This should remove all these cases, right?

I think we wrote down this idea at some point.

**Comment by lancelote** [comment]
>This should remove all these cases, right?

Yeap, it will resolve all of my cases.
