### ISSUE TITLE
pyNose CLI

### ISSUE THREAD

**Issue by QiYuan08** [JetBrains-Research/PyNose#46]
Hi,

Is there anywhere I can find an example command on how to run the tools in CLI because I saw that in the papers but I don't see it anywhere in the repo.

**Comment by WANGJIEKE** [comment]
Hi, if you want to run the original ASE 2021 version, you can find it in the `ASE2021` branch. There's a section in the [`README.md`](https://github.com/JetBrains-Research/PyNose/blob/ASE2021/README.md#cli-mode) describing how to run the original version of the tool from the command line. I hope this will help.

**Comment by QiYuan08** [comment]
Ahh ok I found it 

Thanks a lot  💯
